VRICODE/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VRICODE.Interfaces.Core;
using VRICODE.Models;

namespace VRICODE.Controllers
{
    public class AccountController : Controller
    {
        IUserCore FCore;

        public AccountController(IUserCore ACore)
        {
            FCore = ACore;
        }
        
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(User AUser)
        {
            try {
                FCore.Create(AUser);
                FCore.Save();

                return RedirectToAction("Index", "Home");
            }
            catch(Exception ex)
            {
                return BadRequest(ex);
            }
        }

        [HttpPost]
        public IActionResult SignIn(User AUser)
        {
            try 
            {
                User LUser = FCore.FindBy(t => t.NamUser == AUser.NamUser && t.DesPassword == AUser.DesPassword, true).FirstOrDefault();
                
                if(LUser == null)
                {
                    throw new Exception("Usuário ou senha incorretos");
                }

                HttpContext.Session.SetInt32("NidUser", LUser.NidUser);

                return RedirectToAction("Index", "Home");
            }
            catch(Exception ex)
            {
                return BadRequest(ex);
            }
        }
    }
}

VRICODE/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VRICODE.Interfaces.Core;
using VRICODE.Models;

namespace VRICODE.Controllers
{
    public class ClassController : Controller
    {

        IClassCore FCore;

        public ClassController(IClassCore ACore)
        {
            FCore = ACore;
        }

        public IActionResult Index()
        {
            int nid = (int) HttpContext.Session.GetInt32("NidUser");

            List<Class> LClasses = FCore.FindBy(t => t.UserClasses.Any(s => s.NidUser == nid), true).ToList();

            return View(LClasses);
        }

        public IActionResult Visualization(int ANidClass)
        {
            Class LClass = FCore.Get(ANidClass);
            return View(LClass);
        }

        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Create(Class AClass)
        {
            try {

                FCore.Create(AClass);
                FCore.Save();

                UserClass LUserClass = new UserClass(); 
                var nid = HttpContext.Session.GetInt32("NidUser");

                LUserClass.NidUser = (int) nid;
                LUserClass.NidClass = AClass.NidClass;

                FCore.CreateUserClass(LUserClass);

                return RedirectToAction("Index", "Class");
            }
            catch(Exception ex)
            {
                return BadRequest(ex);
            }
        }

        [HttpPost]
        public IActionResult JoinClass(int ANidClass)
        {
            try
            {
                UserClass LUserClass = new UserClass(); 
                var nid = HttpContext.Session.GetInt32("NidUser");

                LUserClass.NidUser = (int) nid;
                LUserClass.NidClass = ANidClass;

                FCore.CreateUserClass(LUserClass);

                return RedirectToAction("Visualization", "Class", new { ANidClass = ANidClass });
            }
            catch(Exception ex)
            {
                return BadRequest(ex);
            }
        }
    }
}

VRICODE/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VRICODE.Models;

namespace VRICODE.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Group()
        {
            Class LClass = new Class();
            LClass.NamClass = "EPN001";
            LClass.ProblemClasses = new List<ProblemClass>() {
                new ProblemClass() {
                    Problem = new Problem() {
                        DesTitle = "OI"
                    }
                },
                new ProblemClass() {
                    Problem = new Problem() {
                        DesTitle = "Tudo"
                    }
                },
                new ProblemClass() {
                    Problem = new Problem() {
                        DesTitle = "Joia"
                    }
                }
            };

            return View(LClass);
        }

        public IActionResult Create()
        {
            return View();
        }

    }
}

VRICODE/Controllers/ProblemController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using VRICODE.Core.Evaluators;
using VRICODE.Interfaces.Core;
using VRICODE.Models;
using VRICODE.Models.ViewModels;

namespace VRICODE.Controllers
{
    public class ProblemController : Controller
    {

        IProblemCore FCore;

        public ProblemController(IProblemCore ACore)
        {
            FCore = ACore;
        }

        public IActionResult Create(int ANidClass)
        {
            return View(ANidClass);
        }

        [HttpPost]
        public IActionResult Create(Problem AProblem, int ANidClass)
        {
            try
            {
                FCore.Create(AProblem);
                FCore.Save();

                ProblemClass LProblemClass = new ProblemClass();
                LProblemClass.NidClass = ANidClass;
                LProblemClass.NidProblem = AProblem.NidProblem;

                FCore.CreateProblemClass(LProblemClass);    


                return RedirectToAction("Visualization", "Class", new { ANidClass = ANidClass });
            }
            catch (Exception ex)
            {
                return BadRequest(ex);
            }
        }

        public IActionResult Visualization(int id)
        {
            return View(FCore.Get(id));
        }

        public IActionResult Evaluate(int ANidProblem, string ADesCode)
        {
            Problem LProblem = FCore.Get(ANidProblem);

            string[] LInputs = LProblem.ProblemTests.Select(p => p.DesTestInput).ToArray();
            string[] LOutputs = LProblem.ProblemTests.Select(p => p.DesTestExpectedOutput).ToArray();

            EvaluatorOutput LResult = CppCodeEvaluator.Evaluate(ADesCode, LInputs, LOutputs);

            return Json(LResult);
        }
    }
}

VRICODE/Views/Class/Create.cshtml
@{
    ViewData["Title"] = "Turma (Nova)";
}

<form asp-controller="Class" asp-action="Create" method="POST" class="col-xs-8 col-xs-offset-2">
        <div class="row">
            <label class="form-label">Nome</label>
            <input name="NamClass" type="text" class="form-control">
        </div>
            <br>
            <br>
            <button class="btn btn-primary pull-right" type="submit">Salvar Turma</button>
        </div>    
</form>

VRICODE/Views/Class/Index.cshtml
@{
    ViewData["Title"] = "Turmas";
}

@model List<Class>

    <div class="col-xs-12">
        <form asp-action="JoinClass" asp-controller="Class" method="POST">
            <h4>Ingressar em uma turma</h4>
            <div class="col-xs-">
                <input type="text" name="ANidClass" class="col-xs-8" placeholder="Digite o código da Turma:">
            </div>
            <div class="col-xs-2">
                <button type="submit" class="btn btn-primary">Entrar na Turma</button>
            </div>
        </form>
        <div class="col-xs-2">
            <a class="btn btn-primary" href="/Class/Create">Criar nova Turma</a>
        </div>
    </div>
    <div class="col-xs-12">
        <br>    
        <h4>Minhas Turmas</h4>
        <table class="table table-bordered">
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td colspan="3">
                            <span class="form-control">
                                @item.NamClass
                            </span>
                        </td>
                        <td>
                            <a href="/Class/Visualization?ANidClass=@(item.NidClass)" class="btn btn-default">Acessar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

VRICODE/Views/Class/Visualization.cshtml
@model Class

@{
    ViewData["Title"] = Model.NamClass;
}

<a class="btn btn-primary pull-right" href="/Problem/Create?ANidClass=@Model.NidClass">Adicionar Exercicio</a>

<div class="col-xs-8  col-xs-offset-2">
    <h4>Exercícios</h4>
    <table class="table table-bordered">
        <tbody>
            @foreach (var item in Model.ProblemClasses)
            {
                <tr>
                    <td colspan="3">
                        <span class="form-control">
                            @item.Problem.DesTitle
                        </span>
                    </td>
                    <td>
                        <a class="btn btn-default" href="/Problem/Visualization?id=@(item.NidProblem)">Acessar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

VRICODE/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Bem vindo ao VRICode!";
}

<br>
<h3>Resolva os exercícios de sua turma ou crie seus próprios.</h3>
<h5>Envie códigos em C++ e complete os testes</h5>

VRICODE/Views/Problem/Create.cshtml
@{
    ViewData["Title"] = "Exercício (Novo)";
}

@model int
<style>
    #testValues input {
        border: 0;
    }
</style>

<form asp-controller="Problem" asp-action="Create" method="POST" class="col-xs-8 col-xs-offset-2">
            <input type="hidden" name="ANidClass" value="@Model">
            <div class="row">
                <label class="form-label">Título</label>
                <input name="DesTitle" type="text" class="form-control">
            </div>
            <br>
            <div class="row">
                <label class="form-label">Enunciado</label>
                <textarea name="DesProblem" rows="20" class="form-control"></textarea>
            </div>

            <br>

            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                Adicionar Teste
            </button>

            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">Visivel para estudantes</th>
                    <th scope="col">Input</th>
                    <th scope="col">Output</th>
                    <th scope="col"></th>
                    </tr>
                </thead>
                <tbody id="testValues">
                </tbody>
                </table>
            <br>
            <br>
            <button class="btn btn-primary pull-right" type="submit">Salvar Exercício</button>
        </div>    
</form>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <div class="row">
            <div class="col-xs-8 col-xs-offset-2">
                <div class="row">
                    <label class="form-label">Input</label>
                    <input id="inputTest" type="text" class="form-control">
                </div>
                <br>
                <div class="row">
                    <label class="form-label">Output</label>
                    <input id="outputTest" type="text" class="form-control">
                </div>
                <br>
                <div class="row">
                    <label class="form-label">Visivel para estudantes</label>
                    <input id="visibleTest" type="checkbox" checked>
                </div>
            </div>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" onclick="AddTest(event)" class="btn btn-primary">Criar Teste</button>
      </div>
    </div>
  </div>
</div>

<script id="row_template" type="text/template">
    <tr id="{{index}}">
        <td>
            <input type="checkbox" name="ProblemTests[{{index}}].FlgVisibleToUser" value="true" {{checked}}>
            <input type="hidden" name="ProblemTests[{{index}}].FlgVisibleToUser" value="false">
        </td>
        <td><input type="text" readonly name="ProblemTests[{{index}}].DesTestInput" value="{{input}}"/></td>
        <td><input type="text" readonly name="ProblemTests[{{index}}].DesTestExpectedOutput" value="{{output}}"/></td>
        <td><a onclick="RemoveTest(this)"><span class="glyphicon glyphicon-remove"></span> Remover</a></td>
    </tr>
</script>

<script>
    var test_rows = []

    function AddTest(e) {
        var row = $("#row_template").html();

        var input = $("#inputTest").val();
        var output = $("#outputTest").val();
        var visible = $("#visibleTest:checked").length > 0;

        row = row.replace("{{checked}}", (visible ? "checked" : 0));
        row = row.replace("{{input}}", input);
        row = row.replace("{{output}}", output);

        test_rows.push(row);

        fillTable();
    }

    function fillTable() {
        $("#testValues").html("");

        for(var i = 0; i < test_rows.length; i++)
        {
            row = test_rows[i].replace(/{{index}}/g, i);
            $("#testValues").append(row);
        }
    }

    function RemoveTest(obj) {
        var test_index = parseInt($(obj).parent().parent().attr("id"));

        test_rows = test_rows.filter(function(t, index) { return index != test_index; });
        
        fillTable();
    }
</script>

VRICODE/Views/Problem/Visualization.cshtml
@model Problem

@{
    ViewData["Title"] = Model.DesTitle;
}

<style>
    textarea {
        height: 50vh;
        max-width: 100%;
        min-width: 100%;
    }

    .send-button {
        height: 50px;
        border-radius: 0;
        box-shadow: 2px 2px 2px grey;
        background-color: darkslategray;
        color: white;
    }

    .problem-result {
        width: 100%;
        font-weight: bold;
        color: white;
        border-radius: 6px;
        text-align: center;
    }

        .problem-result.success {
            background-color: green;
        }

        .problem-result.failure {
            background-color: red;
        }
</style>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-xs-8 col-xs-offset-2">

                        <code class="row">
                            <label class="form-label" style="display: block">Código</label>
                            <textarea class="code-area" rows="20" type="text" class="form-control"></textarea>
                        </code>
                        <div class="problem-result"></div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn primary send-button" onclick="sendProblemCode(@Model.NidProblem)"><span class="glyphicon glyphicon-import"></span> Enviar Código</button>
            </div>
        </div>
    </div>
</div>

<div class="col-xs-8 col-xs-offset-2" style="padding-bottom: 100px; line-height: 2em; color: grey;">
    <div class="row" style="word-break: break-word;">
        <label class="form-label" style="text-align: justify; font-size: 14px;">
            @Model.DesProblem
        </label>
    </div>

    <br>
    <br>

    <h4>Casos de Teste</h4>
    <hr>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Entrada</th>
                <th scope="col">Saída Esperada</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ProblemTests.Where(t => t.FlgVisibleToUser))
            {
                <tr>
                    <td>@item.DesTestInput</td>
                    <td>@item.DesTestExpectedOutput</td>
                </tr>
            }
        </tbody>
    </table>
    <br>

    <button type="button" class="send-button btn btn-primary col-xs-12" data-toggle="modal" data-target="#exampleModal">
        <span class="glyphicon glyphicon-import"></span> Enviar Tentativa
    </button>

    <br>
    <br>
</div>

<script>
    function sendProblemCode(nidProblem) {
        $('.problem-result').text("");

        $.post({
            url: '@Url.Action("Evaluate", "Problem")',
            data: {
                ANidProblem: nidProblem,
                ADesCode: $('.code-area').val()
            }
        }).done((result) => {
            if (result.status == 0) {
                $('.problem-result').text("Solução aceita!");
                $('.problem-result').removeClass("success failure");
                $('.problem-result').addClass("success");
            }
            else if (result.status == 1) {
                $('.problem-result').text("Erro de Compilação");
                $('.problem-result').removeClass("success failure");
                $('.problem-result').addClass("failure");
            }
            else if (result.status == 2) {
                $('.problem-result').text("Resposta Incorreta");
                $('.problem-result').removeClass("success failure");
                $('.problem-result').addClass("failure");
            }
            else if (result.status == 3) {
                $('.problem-result').text("Tempo Limite Excedido");
                $('.problem-result').removeClass("success failure");
                $('.problem-result').addClass("failure");
            }
        });
    }
</script>

VRICODE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VRICODE</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <partial name="_CookieConsentPartial" />

    <div class="row" style="overflow: auto; margin: 0;">
        <div class="col-xs-10 col-xs-offset-1" style="margin-bottom: 100px; box-shadow: 5px 5px 5px grey; padding: 0;">
            <div class="jumbotron background" style="height: 50vh; color: white; position: relative; border-radius: 0;">
                <a class="pull-left" href="/Home/Index"><span class="glyphicon glyphicon-home"></span> Início</a>
                @if(ViewData["LoginPage"] == null || !((bool)ViewData["LoginPage"]))
                {
                    <a class="pull-right" href="/Account/Index"><span class="glyphicon glyphicon-log-out"></span> Sair</a>
                    <a class="pull-right" href="/Class/Index"><span class="glyphicon glyphicon-tag"></span> Turmas</a>
                }

                <h2 style="position: absolute; bottom: 20px;">@(ViewData["Title"])</h2>
            </div>
            <div class="col-xs-12" style="padding-bottom: 100px; line-height: 2em; color: grey; background-color: white;">
                <br>
                @RenderBody()
            </div>    
        </div>
    </div>


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>